authors=[Jim Schmitz](https\://ixora.io/)
categories=3D
maxRevision=0
minRevision=233
name=Camera 3D
paragraph=Library will execute the draw method multiple times with different camera settings and combine them together to form one composite frame.
prettyVersion=1.3.0
sentence=Alter P3D Rendering to produce Stereoscopic Animations, 360 Video and other 3D effects.
url=https\://ixora.io/projects/camera-3D/
version=8
